# Generated by Django 4.0.2 on 2022-03-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productmodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product.SizeModel', verbose_name='size'),
        ),
    ]
