# Generated by Django 4.0.2 on 2022-04-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productmodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='long_description_EN',
            field=models.TextField(null=True, verbose_name='long description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='long_description_RU',
            field=models.TextField(null=True, verbose_name='long description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='long_description_UZ',
            field=models.TextField(null=True, verbose_name='long description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='name_EN',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='name_RU',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='name_UZ',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_description_EN',
            field=models.TextField(null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_description_RU',
            field=models.TextField(null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_description_UZ',
            field=models.TextField(null=True, verbose_name='short description'),
        ),
    ]
