# Generated by Django 4.0.2 on 2022-04-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productmodel_long_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='long_description_EN',
            new_name='long_description_en',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='long_description_RU',
            new_name='long_description_ru',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='long_description_UZ',
            new_name='long_description_uz',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='name_EN',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='name_RU',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='name_UZ',
            new_name='name_uz',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='short_description_EN',
            new_name='short_description_en',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='short_description_RU',
            new_name='short_description_ru',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='short_description_UZ',
            new_name='short_description_uz',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='CPU_manufacturer',
            field=models.CharField(blank=True, max_length=25, verbose_name='cpu manufacturer'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='Item_name',
            field=models.CharField(blank=True, max_length=244, verbose_name='item name'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='card_description',
            field=models.CharField(blank=True, max_length=199, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='display',
            field=models.CharField(blank=True, max_length=100, verbose_name='display'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='memory_storage',
            field=models.CharField(blank=True, max_length=233, verbose_name='memory storage'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='operating_system',
            field=models.CharField(blank=True, max_length=111, verbose_name='operating system'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='product.brandmodel', verbose_name='brand'),
            preserve_default=False,
        ),
    ]
