# Generated by Django 4.0.2 on 2022-04-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_brandmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.SizeModel', verbose_name='size'),
        ),
    ]
