# Generated by Django 4.0.2 on 2022-04-14 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productmodel_brand_delete_brandmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='CPU_manufacturer',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='Item_name',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='card_description',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='display',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='memory_storage',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='operating_system',
        ),
    ]
