# Generated by Django 4.0.2 on 2022-04-28 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0011_remove_productmodel_cpu_manufacturer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('City', models.CharField(max_length=50, verbose_name='city')),
                ('Country', models.CharField(max_length=50, verbose_name='country')),
                ('zip', models.PositiveIntegerField(max_length=6, verbose_name='zip code')),
                ('name_on_card', models.CharField(max_length=70, verbose_name='verbose_name')),
                ('card_number', models.PositiveIntegerField(max_length=16, verbose_name='card number')),
                ('Exp_month', models.DecimalField(decimal_places=5, max_digits=5, verbose_name='expiration month')),
                ('exp_year', models.PositiveIntegerField(max_length=4, verbose_name='expiration year')),
                ('CVV', models.PositiveIntegerField(max_length=5, verbose_name='CVV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('product', models.ManyToManyField(to='product.ProductModel')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
