# Generated by Django 4.0.2 on 2022-05-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='CVV',
            field=models.PositiveIntegerField(verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='card_number',
            field=models.PositiveIntegerField(verbose_name='card number'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='exp_year',
            field=models.PositiveIntegerField(verbose_name='expiration year'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='zip',
            field=models.PositiveIntegerField(verbose_name='zip code'),
        ),
    ]
